on: [push]

name: Tests

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv --fork-url https://speedy-nodes-nyc.moralis.io/cede2bf2868b0e93070abef2/eth/mainnet/archive